version: "3"
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8020:8020"
      - "8030:8030"
      - "8040:8040"
    depends_on:
      - ipfs
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: host.docker.internal
      postgres_user: postgres
      postgres_pass: mehedi2580
      postgres_db: graph-node
      ipfs: "http://host.docker.internal:5001"
      ethereum: "mainnet:http://host.docker.internal:8545"
      GRAPH_LOG: info
  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - "5001:5001"
    volumes:
      - ./data/ipfs:/data/ipfs
